function git_prompt_info() {
  local ref
    ref=$(command git symbolic-ref HEAD 2> /dev/null) || \
    ref=$(command git rev-parse --short HEAD 2> /dev/null) || return 0
    echo " ${ref#refs/heads/}$(parse_git_dirty)"
}

# Checks if working tree is dirty
function parse_git_dirty() {
  local STATUS=''
  local FLAGS
  FLAGS=('--porcelain')
      FLAGS+='--ignore-submodules=dirty'
      FLAGS+='--untracked-files=no'
    STATUS=$(command git status ${FLAGS} 2> /dev/null | tail -n1)
  if [[ -n $STATUS ]]; then
    echo " * "
  else
    echo ""
  fi
}

# Aliases
alias ll='ls -l'
alias la='ls -la'
alias path="echo $PATH | sed 's/:/\n/g'"
alias v='vim'

autoload -U zutil
autoload -U compinit
autoload -U complist
autoload -U promptinit
promptinit
setopt prompt_subst
compinit -i

PROMPT='%B%(?..[%?] )%b%n@%U%m%u$(git_prompt_info)%# '

# Uncomment this line if you want jobs in background to contiue processing when exiting shell. One can also run the command 'disown' on the job to let the shell forget about the job (or start it with &| or &! at the end of the line) 
#setopt NO_HUP

# Uncomment following line to AUTO_CD if command is a directory
setopt AUTO_CD
setopt NO_BEEP
setopt EXTENDED_GLOB

# Allows commands like 'echo foo > file1 > file2'
setopt MULTIOS
setopt CORRECT

# Set colors
autoload colors; colors;
export LSCOLORS="Gxfxcxdxbxegedabagacad"
if [ "$DISABLE_LS_COLORS" != "true" ]
then
    # Find the option for using colors in ls, depending on the version: Linux or BSD
    ls --color -d . &>/dev/null 2>&1 && alias ls='ls --color=tty' || alias ls='ls -G'
fi

# One history for all open shells; store 10 000 entries. Use ^R and Alt-P
HISTFILE=~/.zhistory
HISTSIZE=SAVEHIST=10000
setopt incappendhistory
setopt sharehistory
setopt extendedhistory

# Useful to remember command in history without executing them
setopt interactivecomments

# Add tab completion to "cd.."
zstyle ':completion:*' special-dirs true

export PATH=$PATH:/usr/local/share/npm/bin

export PATH=~/bin:$PATH



source ~/.profile

#/home/lmohseni/builds/xcape/xcape -e 'Control_L=Escape'

alias daystamp='date +%Y%m%d'

export GOPATH=$HOME/projects/go
export PATH=$PATH:$GOPATH/bin


zstyle ':completion:*' verbose yes

zstyle ':completion:*:descriptions' format '%B%d%b'

zstyle ':completion:*:messages' format '%d'

zstyle ':completion:*:warnings' format 'No matches for: %d'

zstyle ':completion:*' group-name ''

fpath=(~/configs/completions $fpath)

alias hr='print ${(l:COLUMNS::=:)}'

alias info='info --vi-keys'


bindkey ' ' magic-space

alias got='git'

alias mvnlaunch="mvn -Plocal,local-deploy clean deploy -Dmaven.test.skip=true"

setopt NO_NOMATCH

export TOMCAT_HOME=~/builds/tomcat

alias mvndefault="mvn -Plocal,liquibase-update,local-deploy clean deploy"
alias mvnall="git stash; git fetch; git rebase origin/maven-trunk; git stash apply; mvndefault"

alias factor="~/builds/factor/factor -run=listener"

export PATH=/home/lmohseni/builds/erl/bin:$PATH

export PATH=/usr/share/chicken/bin:$PATH

export CHICKEN_DOC_PAGER=less
export CHICKEN_DOC_COLORS=auto

set -o vi

export PATH=/usr/local/bin:$PATH

